### ISSUE TITLE
Possibility to add list of all versions in options attribute

### ISSUE THREAD

**Issue by janfabian** [citkane/typedoc-plugin-versions#17]
Hi, would that be possible ? 

```
"plugin": ["typedoc-plugin-versions"],
"versions": { 
  ... 
  "versions": ["0.0.1", "0.0.2"...]
}
```

**Comment by toebeann** [comment]
To what end?

**Comment by janfabian** [comment]
I planned to collect all tags via GitHub public API and provide them directly to your plugin. But then I quickly scanned through the code and readme and it seems quite against the concept. 

Feel free to close this issue

**Comment by janfabian** [comment]
I originally ended up here, because I wanted to provide the same functionality to my typedoc generated pages as your plugin does. But I want to avoid copying the old docs back and forth with the new version folder. Anyway I'm probably gonna use it the same way as it's in your GH example workflow

**Comment by toebeann** [comment]
> I planned to collect all tags via GitHub public API and provide them directly to your plugin. But then I quickly scanned through the code and readme and it seems quite against the concept. 
> 
> Feel free to close this issue 

Ah, to have all the old versions rebuilt against their versions? This is something I have planned as a future addition to the sister project to this plugin, a CLI tool for use in the CI/CD environment. It hasn't yet been added to it because it's still a work in progress and I haven't had as much time for that project of late than is ideal.

**Comment by toebeann** [comment]
https://github.com/toebeann/typedoc-plugin-versions-cli is the sibling CLI tool, there is an open issue over there for tracking adding the functionality for rebuilding all the old version tags against their git tags, assuming that is what you wanted. I'll try to get back to adding that feature sometime soon :)

**Comment by toebeann** [comment]
> I planned to collect all tags via GitHub public API and provide them directly to your plugin. But then I quickly scanned through the code and readme and it seems quite against the concept. 

Ah, to have the previous versions built against their git version tags? This is something I have planned as a future addition to the sister project to this plugin, a CLI tool for use in the CI/CD environment: https://github.com/toebeann/typedoc-plugin-versions-cli

There is an open issue over there for adding the functionality for building old doc versions against their git tags ([toebeann/typedoc-plugin-versions-cli#3](https://github.com/toebeann/typedoc-plugin-versions-cli/issues/3)), assuming that is what you wanted. I'll try to get back to adding that feature sometime soon :)

If this is what you want, then this issue is a duplicate of #13

**Comment by janfabian** [comment]
Cool :star: , closing in favor of #13 and watching the cli repo
